# Generated by Django 5.2.3 on 2025-06-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorapplication',
            old_name='qualifications',
            new_name='specialization',
        ),
    ]
