# Generated by Django 5.2.3 on 2025-06-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctorprofile_availability_education_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
