# Generated by Django 5.2.3 on 2025-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_doctorprofile_user_remove_education_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='about_you',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='education',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='specialization1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='specialization2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='specialization3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='specialization4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
