# Generated by Django 5.2.3 on 2025-06-26 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctorapplication_about_you_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField()),
                ('specialization1', models.CharField(max_length=200)),
                ('specialization2', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization3', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization4', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('about_you', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.doctorapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_off', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.doctorprofile')),
            ],
        ),
    ]
