# Generated by Django 5.2.3 on 2025-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctorprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='official_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='official_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
