# Generated by Django 5.2.3 on 2025-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctorapplication_official_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='doctor_profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='doc_profile_pic/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='doc_profile_pic_profile/'),
        ),
    ]
