# Generated by Django 5.2.3 on 2025-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_doctorapplication_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='doctor_profile_pic',
            field=models.FileField(default='default.png', upload_to='doc_profile_pic/'),
        ),
    ]
