# Generated by Django 5.2.3 on 2025-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_doctorapplication_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee in INR', max_digits=8),
        ),
    ]
