# Generated by Django 5.2.3 on 2025-06-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_doctorapplication_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorapplication',
            name='consultation_fee',
        ),
    ]
