# Generated by Django 5.2.3 on 2025-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='patients_treated',
            field=models.IntegerField(default=0),
        ),
    ]
