# Generated by Django 5.2.3 on 2025-07-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appointment_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/')),
                ('extracted_report', models.TextField()),
                ('report_test_name', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('precautions', models.TextField()),
                ('emergency', models.CharField(max_length=50)),
                ('recommended_specializations', models.TextField(help_text='Comma separated specializations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
